<?php
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * {@inheritdoc}
 */
function pixies_content_pack_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.pixies_content_pack':
      $output = '';
      $output .= '<h3>' . t("pixiekat's content pack ♡") . '</h3>';
      $output .= '<p>' . t('a collection of content development and cms modules for drupal by pixiekat.') . '</p>';
      return $output;

    default:
  }
}


function pixies_content_pack_preprocess_social_media_links_platforms(array &$variables) {
  $variables['social_media_links_description'] = t('find me on social media. be warned, i hate it as much as you.');
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function pixies_content_pack_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  switch ($hook) {
    case 'social_media_links_platforms':
      $suggestions[] = $hook . '__' . 'custom';
      break;
  }
}


/**
 * Implements hook_theme().
 */
function pixies_content_pack_theme($existing, $type, $theme, $path) {

  $ret = [];

  $moduleHandler = \Drupal::service('module_handler');
  if ($moduleHandler->moduleExists('social_media_links')) {
    $ret['social_media_links_platforms__custom'] = [
      'base hook' => 'social_media_links_platforms',
      'path' => $path . '/templates/social_media_links',
    ];
  }

  return $ret;

}
